/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package threadwithpacher2;

import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import jdk.nashorn.internal.parser.TokenType;

/**
 *
 * @author micha
 */
public class GUI extends javax.swing.JFrame {
    
    private JTable table;
    private Model_BL model;
    private final String path = System.getProperty("user.dir") + File.separator + "src" +File.separator + "Data" + File.separator;
    
    public GUI() {
        this.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        this.setSize(600, 700);
        this.setLocationRelativeTo(null);
        model = new Model_BL();
        JPanel hautpanel = new JPanel();
        hautpanel.setLayout(new java.awt.BorderLayout());
        table = new JTable();
        JScrollPane scroll = new JScrollPane();
        table.setModel(model);
        scroll.setViewportView(table);
        
        JPanel setting = new JPanel();
        setting.setLayout(new java.awt.GridLayout(1, 2, 1, 1));
        JButton neuePerson = new JButton();
        neuePerson.setAction(new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                PersonHinzu();
            }
        });
        
        JButton Speichern = new JButton();
        
        Speichern.setAction(new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                sichern(1);
            }
        });
        JButton Laden = new JButton();
        
        Laden.setAction(new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                sichern(2);
            }
        });
        
        JButton loadUselessData = new JButton("TestData");
        
        loadUselessData.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                sichern(3);
            }
        });
        setting.add(Speichern);
        setting.add(Laden);
        setting.add(neuePerson);
        setting.add(loadUselessData);
        Laden.setText("Daten laden");
        Speichern.setText("Daten speichern");
        neuePerson.setText("Neue Person erstellen");
        
        hautpanel.add(setting, BorderLayout.NORTH);
        hautpanel.add(scroll, BorderLayout.CENTER);
        this.getContentPane().add(hautpanel);
        
    }
    
    public void sichern(int i) {
               
        switch(i){
            case 1: 
                model.speichernTxt(path + "Personendaten.txt");
                break;
            case 2:
                model.einlesenTxt(path + "Personendaten.txt");
                break;
            case 3:
                model.testdaten(path + "Personen.txt");
        }
        
    }
    
    public void PersonHinzu() {
        
        Person_Hinzu hinzu = new Person_Hinzu(this, true);
        hinzu.setVisible(true);
        if (hinzu.getIsKorrekt()) {
            Person p = hinzu.getPerson();
            model.add(p);
            model.update();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 301, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
