/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package threadwithpacher2;

import java.awt.event.ActionEvent;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.AbstractAction;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author micha
 */
public class Person_Hinzu extends javax.swing.JDialog {

    private JTextField vn, nn, adresse, geb, mon, gen;
    private Person p;
    private boolean isKorrekt = false;

    public Person_Hinzu(java.awt.Frame parent, boolean modal) {
        super(parent, modal);

        this.setSize(700, 400);
        vn = new JTextField();
        nn = new JTextField();
        adresse = new JTextField();
        geb = new JTextField();
        mon = new JTextField();
        gen = new JTextField();

        JPanel hauptpanel = new JPanel();
        hauptpanel.setLayout(new java.awt.GridLayout(7, 2, 1, 1));
        hauptpanel.add(new JLabel("Vorname:"));
        hauptpanel.add(vn);
        hauptpanel.add(new JLabel("Nachname:"));
        hauptpanel.add(nn);
        hauptpanel.add(new JLabel("Adresse:"));
        hauptpanel.add(adresse);
        hauptpanel.add(new JLabel("Geburtsdatum:"));
        hauptpanel.add(geb);
        hauptpanel.add(new JLabel("Money:"));
        hauptpanel.add(mon);
        hauptpanel.add(new JLabel("Geschlächt:"));
        hauptpanel.add(gen);

        JButton btexit = new JButton();

        btexit.setAction(new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                dispose();
            }
        });
        JButton btstart = new JButton();

        btstart.setAction(new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                check();
            }
        });

        btexit.setText("Exit");
        btstart.setText("Fertig");
        hauptpanel.add(btexit);

        hauptpanel.add(btstart);

        getContentPane()
                .add(hauptpanel);

    }

    public void check() {
        boolean isOk = false;

        //while (isOk == false) {
        try {
            p = new Person(vn.getText(), nn.getText(), LocalDate.parse(geb.getText(), DateTimeFormatter.ISO_DATE).toString(), adresse.getText(), Double.parseDouble(mon.getText()));
            isOk = true;
            isKorrekt = true;
            dispose();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Fehler!");
        }
        //  }

    }

    public void exit() {
        dispose();
    }

    public Person getPerson() {
        return p;
    }

    public boolean getIsKorrekt() {
        return isKorrekt;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Person_Hinzu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Person_Hinzu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Person_Hinzu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Person_Hinzu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Person_Hinzu dialog = new Person_Hinzu(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
